### ISSUE TITLE
Syntax error on Internet Explorer 11

### ISSUE THREAD

**Issue by jhofman** [QuentinAndre/DistributionBuilder#2]
@QuentinAndre it looks like Distribution Builder is failing on Internet Explorer 11 with the following syntax error on a basic example (below):

  `SCRIPT1002: Syntax error, distributionbuilder.min.js (1,1069)`

Any idea what might be causing this and how easy it is (or isn't) to fix?

I know IE bugs are a pain, greatly appreciate any help you can provide!

Thanks.

```
<html>
  <head>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
    
    <link rel="stylesheet" href="https://cdn.rawgit.com/QuentinAndre/DistributionBuilder/master/distributionbuilder.css">
    <script src="https://cdn.rawgit.com/QuentinAndre/DistributionBuilder/master/distributionbuilder.min.js"></script>


    <script>
      // var $j = jQuery.noConflict();
      
      $j(document).ready(function() {
        var distbuilder = new DistributionBuilder();
        distbuilder.render("targetdiv");
        distbuilder.labelize();
      });
    </script>

  </head>


  <body>
    <div id="targetdiv"></div>
  </body>

</html>
```

**Comment by jhofman** [comment]
P.S. I also tried including the commented-out lines, but to no effect. The error reproduces if you remove the entire `<script>` block of javascript, seems to be from just the loading of `distributionbuilder.min.js` itself.

**Comment by QuentinAndre** [comment]
Hi Jake,

It's been a while since I touched the code, but I suspect that the transpiled code was not created to target IE11 by default.

I will check if there is an easy way to transpile the library into IE compatible code in the next few days, I'm keeping you posted.

**Comment by jhofman** [comment]
Terrific, thanks for the quick reply and for checking!

**Comment by jhofman** [comment]
@QuentinAndre: is it possible that [this](https://stackoverflow.com/questions/36723931/javascript-error-in-typescript-generated-js-in-ie11) is a solution, just switching to es5 from es6?

trying to do the typescript compilation myself but sadly running into some issues because i'm new to typescript.

**Comment by QuentinAndre** [comment]
Hi Jake,

Yep, sorry for the delay: I just moved, and changed computer, so I have to rebuild my dev environment from scratch.

Expect a working version of the library tomorrow, I'm getting close!

**Comment by jhofman** [comment]
No worries. I've managed to break my node installation in the process of debugging this!

I did get further: it's the class keyword that's the source of the issue, and using https://babeljs.io/en/repl to transpile the minified `distributionbuilder.min.js` file to es2015 does solve the problem, although I had to use the following two hacks for missing polyfills to get everything working:

  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill#Polyfill
  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill

So if there happens to be a way to go straight to es5, terrific! If not I can probably live with this hacked version.

Thanks!

**Comment by QuentinAndre** [comment]
Hey Jake,

Yep, JS programming is insanely annoying, and I stopped counting the number of time I broke my node installation while developing :).

I'll think of the best way of releasing a new version of the library, but for now you can already find a IE9+ version on the following gist:

https://gist.github.com/QuentinAndre/ae8cd067a45d84078f9a4ad9f4d267b4

I tested it on IE11, and it works on my machine. Could you confirm that it works on yours?

**Comment by jhofman** [comment]
Fantastic. Tested this and it works great, thank you!

Btw, if it's easy to relay, can you share the `tsconfig.json` and/or compilation commands that generated this? Curious to learn how to do this properly.

**Comment by QuentinAndre** [comment]
No problem! I have uploaded the changes that I made to another branch, [distbuilder-dev](https://github.com/QuentinAndre/DistributionBuilder/tree/distbuilder-dev).

The exact changes are:
* Import the ES6 polyfills in the source code of the library:
```/** IE9, IE10 and IE11 requires all of the following polyfills. **/
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
```

* Change the argument `target` in `tsconfig.json` to compile the library targeting ES5 (which makes it compatible with IE9+):

```
{
  "compilerOptions": {
    "declaration": true,
    "lib": ["dom", "es6"],
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "noUnusedLocals": true,
    "outDir": "./lib",
    "target": "es5",
    "strict": true,
    "strictNullChecks": false,
    "suppressImplicitAnyIndexErrors": true,
    "types": []
  },
  "include": ["src/*"]
}
```

One of the dependencies was not compiling properly, so I also had to change a line in `package.json`, but I suspect it is specific to my machine.

**Comment by jhofman** [comment]
Great, thanks!

And do you compile w/ `tsc`? `webpack`? Something else? (Sorry for the newbie questions.)

**Comment by QuentinAndre** [comment]
I use the [Yarn package manager](https://yarnpkg.com/), so I simply `yarn build`, but I assume results would be identical using tsc or webpack. I'm also very much a newbie, so I go by the first thing that works and is reproducible across my machines ;).
